---
- name: Deploy MERN Application
  hosts: all
  become: true
  gather_facts: no
  vars:
    ansible_become_pass: "Raghu@2004"

  tasks:
    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: "docker-compose.yml"

    - name: Run Docker Compose
      command: docker-compose up -d